### PR TITLE
Basic changes to the site

### PR DESCRIPTION
**Pull request by BaerLKR**
Hello,
I know it isn't a lot but it is a start. I will continue working on it but I don't really know in what direction this should go.
So I thought why not make a PR and discuss it over there.
Hope you like it <3

### CODE REVIEW

**Comment by Pegasust** [comment]
I feel like the icons for GitHub, Twitter, and other social media should be in hindsight, preferably on top right instead of being obscured into the crab icon.

The posted video on discord was necessary for me to discover that there are such buttons, so we really want the user to seek for these social links without any obscurity.

**Comment by BaerLKR** [comment]
Even though that is a good point I think that the text is more important than for example the twitter of crablang.
So I am not sure on how to decide rn. Maybe we could add some way of drawing the users attention to the button (saying that the contact means are there)?

**Comment by Pegasust** [comment]
I would just use SVG of these social media and obscure the button onto the background. 

The user sees a hint of GitHub icon and Twitter icon on the top right, but most of it is transparent, only the outlines are there semi-transparent to hint the user that social media can be found on the top right

Regarding your comment on drawing users' attention to the button, couple of options:
a) I honestly think show-on-hover would be better than show-on-click. 
b) Having specific icon for Crablang's social media would be another simple fix. 
c) A more accessible (but unnecessarily complicated), is to display the social media for a split second and collapse that onto the button that you have now.

**Comment by BaerLKR** [comment]
Maybe a small banner that shows on page load and then moves behind the button. If I understand your suggestion correctly that would go in the direction of the third idea

**Comment by BaerLKR** [comment]
The simplest fix is to just have it expanded by default i guess

**Comment by trvswgnr** [comment]
we're going to stick with a simpler theme for now. maybe we'll revisit this later.

**Pull request closed without merging**
